version: '3.8'
services:

  web:
    image: nginx
    ports: 
      - 8000:80
    volumes:
      - ./www.prolocosansalvatoretelesino.it:/usr/share/nginx/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
