version: '3.8'
services:

  web:
    image: nginx
    container_name: web
    hostname: web
    ports: 
      - 8000:80
    volumes:
      - ./website:/var/www/html:rw
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    image: php:8-fpm
    container_name: php-fpm
    hostname: php-fpm
    volumes:
      - ./website:/var/www/html:rw